eid=15
name=Hemanth Kumar Konakalla
salary=150000
address=Hyderabad
companyName=Infosys
companyType=SoftwareService
ceo=NarayanaMurthy
streetName=AshokNagar
landMark=Near TTD Kalyana Mandapam
pincode=534312